### ISSUE TITLE
"TypeError: 'staticmethod' object is not callable" with python 3.9.2

### ISSUE THREAD

**Issue by ef15c** [chomupashchuk/ariston-remotethermo-api#7]
Hello,

Thank you for your great API.

However, I encountered an error when I run it with python 3.9.2

Traceback (most recent call last):
  File "/mnt/md1/svn/ariston/trunk/test_ariston_net.py", line 8, in <module>
    from aristonremotethermo.ariston import AristonHandler
  File "/home/xxx/.local/lib/python3.9/site-packages/aristonremotethermo/__init__.py", line 1, in <module>
    from . import ariston
  File "/home/xxx/.local/lib/python3.9/site-packages/aristonremotethermo/ariston.py", line 12, in <module>
    class AristonHandler:
  File "/home/xxx/.local/lib/python3.9/site-packages/aristonremotethermo/ariston.py", line 402, in AristonHandler
    append_param(sensor, _MAP_ARISTON_MULTIZONE_PARAMS, _SENSOR_SET_LIST)
TypeError: 'staticmethod' object is not callable

On two other machines, I can use the API without any problem, with python 3.10.9

Thank you very much.

**Comment by romicaiarca** [comment]
Same issue here on MacOS, python3.
